# WideDTA
General:
  fast_dev_run: False
  random_seed: 42
  early_stop: False
  min_delta: 0.001
  patience_epochs: 10

Dataset:
  name: "bindingdb_kd"
  path: "data"
  label_to_log: True
  harmonize_affinities: True

Encoder:
  num_filters: 32
  kernel_size: 2
  embedding_dim: 128

  Drug:
    sequence_length: 85
  Target:
    sequence_length: 1000
  Motif:
    sequence_length: 500

Decoder:
  # MPL
  in_dim: 192
  hidden_dim: 1024
  out_dim: 512
  dropout_rate: 0.3
  num_fc_layers: 3

Trainer:
  ci_metric: True
  train_batch_size: 200
  test_batch_size: 200
  min_epochs: 0
  max_epochs: 100
  learning_rate: 0.003
