General:
  random_seed: 42
  output_dim: 128
  early_stop: False
  min_delta: 0.001
  patience_epochs: 20

Dataset:
  name: DAVIS
  path: ./data

Preprocessing:
  Target:
    MSA:
      hhblits_db_path: r"C:\Users\raulc\code\projeto_ifá\data\hhsuite\UniRef30_2023_02_hhsuite"
      hhblits_bin: r"wsl /home/raulc/miniconda3/condabin/conda run -n ifa_linux hhblits"
      hhfilter_bin: r"wsl /home/raulc/miniconda3/condabin/conda run -n ifa_linux hhfilter"
      max_filter: 100000
      realign_max: 100000
      block_size: 100000
      max_lines_in_summary: 100000
      iterations: 3
      e_value_th: 0.001
      cpu_threads: 8

    Filter:
      id_th: 90

Encoder:
  Drug:
    input_dim: 78
    output_dim: 128

  Target:
    input_dim: 54
    output_dim: 128

Decoder:
  # MPL
  input_dim: 256
  hidden_dim: 1024
  output_dim: 1
  dropout_rate: 0.2
  include_decoder_layers: False

Trainer:
  ci_metric: True
  train_batch_size: 512
  test_batch_size: 512
  min_epochs: 0
  max_epochs: 2 #1000
  learning_rate: 0.0005
