General:
  fast_dev_run: False
  random_seed: 42
  output_dim: 96
  early_stop: False
  min_delta: 0.001
  patience_epochs: 20

Dataset:
  name: "davis"
  path: "data"

Encoder:
  num_filters: 32
  kernel_size: 2
  embedding_dim: 128

  Drug:
    num_embeddings: 1993
    sequence_length: 85
  Target:
    num_embeddings: 7932
    sequence_length: 1000
  Motif:
    num_embeddings: 2344
    sequence_length: 500

Decoder:
  # MPL
  in_dim: 1024
  hidden_dim: 512
  dropout_rate: 0.3
  num_fc_layers: 3

Trainer:
  ci_metric: True
  train_batch_size: 256
  test_batch_size: 256
  min_epochs: 0
  max_epochs: 3
  learning_rate: 0.003
