General:
  fast_dev_run: True
  random_seed: 42
  output_dim: 96
  early_stop: False
  min_delta: 0.001
  patience_epochs: 20

Dataset:
  name: "davis"
  path: "data"

Encoder:
  Drug:
    sequence_length: 10
    num_filters: 16
    kernel_size: 2
  Target:
    sequence_length: 6729
    num_filters: 16
    kernel_size: 2
  Motif:
    sequence_length: 1076
    num_filters: 16
    kernel_size: 2

Decoder:
  # MPL
  in_dim: 5120
  hidden_dim: 512
  dropout_rate: 0.1
  num_fc_layers: 3

Trainer:
  ci_metric: True
  train_batch_size: 256
  test_batch_size: 256
  min_epochs: 0
  max_epochs: 3
  learning_rate: 0.003
