# GraphDTA
General:
  fast_dev_run: False
  random_seed: 42
  output_dim: 128
  early_stop: False
  min_delta: 0.001
  patience_epochs: 10

Dataset:
  name: "davis"
  path: "data"
  label_to_log: True
  harmonize_affinities: False

Encoder:
  GAT:
    input_dim: 78
    num_heads: 8
    output_dim: 128
  GCN:
    input_dim: 78
    output_dim: 128
  GIN:
    input_dim: 78
    num_filters: 32
    output_dim: 128
  GAT_GCN:
    input_dim: 78
    num_heads: 32
    output_dim: 128

  Target:
    # CNN
    embedding_dim: 128
    num_embeddings: 25
    sequence_length: 1200
    num_filters: 32
    num_conv_layers: 3
    kernel_size: 8

Decoder:
  # MPL
  in_dim: 224
  hidden_dim: 1024
  out_dim: 512
  dropout_rate: 0.2
  num_fc_layers: 3

Trainer:
  ci_metric: True
  train_batch_size: 512
  test_batch_size: 512
  min_epochs: 0
  max_epochs: 100
  learning_rate: 0.0005
